name: Semantic Pull Requests
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  main:
    uses: peak-platform/.github/.github/workflows/semantic-pr.yml@c4dfc821563871a9112b31b164161bc4a76eb24b  # main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
